/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'Szymon' at '22.09.16 15:45' with Gradle 2.13
 *
 * @author Szymon, @date 22.09.16 15:45
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
